/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrefacePanel.java
 *
 * Created on 16-aug-2012, 13:27:16
 */
package viewControllers.menu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Robin jr
 */
public class PrefacePanel extends javax.swing.JPanel {

    /** Creates new form PrefacePanel */
    public PrefacePanel(MainFrame parent) {
	this.parent = parent;
	
	initComponents();
	addListeners();
    }
    
    private void addListeners(){
	// connect the manage decks button
	this.manageDecksOutlet.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent e) {
		parent.createDeck();
	    }
	});
	
	// connect the offline button
	this.playOfflineOutlet.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent e) {
		parent.playOffline();
	    }
	});
	
	// connect the online button
	this.playOnlineOutlet.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent e) {
		parent.playOnline();
	    }
	});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        manageDecksOutlet = new javax.swing.JButton();
        playOfflineOutlet = new javax.swing.JButton();
        playOnlineOutlet = new javax.swing.JButton();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 0, 30));

        manageDecksOutlet.setText("Manage decks");
        jPanel1.add(manageDecksOutlet);

        playOfflineOutlet.setText("Play offline");
        jPanel1.add(playOfflineOutlet);

        playOnlineOutlet.setText("Play online");
        jPanel1.add(playOnlineOutlet);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageDecksOutlet;
    private javax.swing.JButton playOfflineOutlet;
    private javax.swing.JButton playOnlineOutlet;
    // End of variables declaration//GEN-END:variables
    private final MainFrame parent;

}
