/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BackgroundFrame.java
 *
 * Created on Dec 13, 2011, 10:33:14 PM
 */
package viewControllers;

import viewControllers.menu.MainFrame;
import images.ImageLoader;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.UserData;

/**
 *
 * @author Warkst
 */
public class BackgroundFrame extends javax.swing.JFrame {
    
    private MainFrame delegate;
    private UserData model;
    
    /** Creates new form BackgroundFrame */
    public BackgroundFrame(MainFrame delegate, UserData model) {
	this.delegate = delegate;
	this.model = model;
	
	initComponents();
	
	// same as cancel
	this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	
	// center it somewhat
	this.setLocationRelativeTo(null);
	
	this.backgroundList.setListData(model.getBackgrounds());
	this.backgroundList.setSelectedValue(model.getUserBackground(), true);
	
	setPreview(model.getUserBackground());
    }
    
    private void setPreview(String background){
	ImageIcon icon = new ImageIcon(ImageLoader.createImageIconAtHomeLocation(background).getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH));
	this.imageLabel.setIcon(icon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundScroller = new javax.swing.JScrollPane();
        backgroundList = new javax.swing.JList();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 570, 350));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(570, 350));
        setMinimumSize(new java.awt.Dimension(570, 350));
        setPreferredSize(new java.awt.Dimension(570, 350));

        backgroundScroller.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        backgroundScroller.setMaximumSize(new java.awt.Dimension(150, 260));
        backgroundScroller.setMinimumSize(new java.awt.Dimension(150, 260));
        backgroundScroller.setPreferredSize(new java.awt.Dimension(150, 260));
        backgroundScroller.setSize(new java.awt.Dimension(150, 260));

        backgroundList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        backgroundList.setSize(new java.awt.Dimension(100, 136));
        backgroundList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                backgroundListValueChanged(evt);
            }
        });
        backgroundScroller.setViewportView(backgroundList);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setMaximumSize(new java.awt.Dimension(400, 300));
        imageLabel.setMinimumSize(new java.awt.Dimension(400, 300));
        imageLabel.setPreferredSize(new java.awt.Dimension(400, 300));
        imageLabel.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Preview");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(saveButton))
                    .add(layout.createSequentialGroup()
                        .add(backgroundScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(backgroundScroller, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cancelButton)
                            .add(saveButton)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_backgroundListValueChanged
//	System.out.println("ListSelectionChanged!");
	if (!evt.getValueIsAdjusting()) {
//	    System.out.println("\tto value: "+backgroundList.getSelectedIndex());
	    setPreview((String)backgroundList.getSelectedValue());
	}
    }//GEN-LAST:event_backgroundListValueChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
	// 
	model.setUserBackground((String)backgroundList.getSelectedValue());
	delegate.disposeBackgroundFrame(this);
	// dispose
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList backgroundList;
    private javax.swing.JScrollPane backgroundScroller;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
