/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardFrame.java
 *
 * Created on Dec 13, 2011, 3:18:54 PM
 */
package viewControllers;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import model.Card;

/**
 *
 * @author Warkst
 */
public abstract class CardFrame extends javax.swing.JFrame {
    
    Card card;

    /** Creates new form CardFrame */
    public CardFrame(Card card) {
	this.card = card;
		
	initComponents();
	
	this.setLocationRelativeTo(null);
	
	// set font: http://javatechniques.com/blog/setting-jtextpane-font-and-color/
	
	this.setTitle(card.getName());
	
	this.setFields();
	
	this.addKeyListener(new KeyListener() {

	    @Override
	    public void keyTyped(KeyEvent e) {
		//
	    }

	    @Override
	    public void keyPressed(KeyEvent e) {
		System.out.println("Key Pressed!");
		if(e.getKeyCode() == KeyEvent.VK_W && e.isMetaDown()){
		    CardFrame.this.dispose();
		}
	    }

	    @Override
	    public void keyReleased(KeyEvent e) {
		//
	    }
	});
    }
    
    public void electFirstResponder(){
	this.requestFocus();
    }
    
    protected abstract void setFields();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        bottomRightLabel = new javax.swing.JLabel();
        bottomLeftLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        typesLabel = new javax.swing.JLabel();
        rulesScroller = new javax.swing.JScrollPane();
        rulesArea = new javax.swing.JEditorPane();
        rnsLabel = new javax.swing.JLabel();
        tagsLabel = new javax.swing.JLabel();
        restrictionsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        nameLabel.setText("Name");
        nameLabel.setFocusable(false);

        bottomRightLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bottomRightLabel.setText("bottom_right");
        bottomRightLabel.setFocusable(false);

        bottomLeftLabel.setText("bottom_left");
        bottomLeftLabel.setFocusable(false);

        costLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        costLabel.setText("Cost");
        costLabel.setFocusable(false);

        typesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        typesLabel.setText("(Supertype) Type - Subtype");
        typesLabel.setFocusable(false);

        rulesArea.setContentType("text/html");
        rulesArea.setEditable(false);
        rulesArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        rulesArea.setFocusable(false);
        rulesScroller.setViewportView(rulesArea);

        rnsLabel.setFont(new java.awt.Font("Lucida Grande", 2, 8));
        rnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rnsLabel.setText("rarity - number - set");
        rnsLabel.setFocusable(false);

        tagsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        tagsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tagsLabel.setText("Tags");
        tagsLabel.setFocusable(false);

        restrictionsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        restrictionsLabel.setText("Restrictions");
        restrictionsLabel.setFocusable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, rulesScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, restrictionsLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .add(rnsLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(bottomLeftLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(bottomRightLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(nameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(costLabel))
                    .add(layout.createSequentialGroup()
                        .add(typesLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tagsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(costLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(typesLabel)
                    .add(tagsLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(restrictionsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rulesScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bottomRightLabel)
                    .add(bottomLeftLabel))
                .add(4, 4, 4)
                .add(rnsLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel bottomLeftLabel;
    protected javax.swing.JLabel bottomRightLabel;
    protected javax.swing.JLabel costLabel;
    protected javax.swing.JLabel nameLabel;
    protected javax.swing.JLabel restrictionsLabel;
    protected javax.swing.JLabel rnsLabel;
    protected javax.swing.JEditorPane rulesArea;
    protected javax.swing.JScrollPane rulesScroller;
    protected javax.swing.JLabel tagsLabel;
    protected javax.swing.JLabel typesLabel;
    // End of variables declaration//GEN-END:variables
}
