/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadingScreen.java
 *
 * Created on Dec 13, 2011, 9:24:43 PM
 */
package viewControllers;

import images.ImageLoader;
import javax.swing.JFrame;

/**
 *
 * @author Warkst
 */
public class LoadingScreen extends javax.swing.JFrame {

    /** Creates new form LoadingScreen */
    public LoadingScreen() {
	initComponents();
	
	this.setLocationRelativeTo(null);
	
	this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//	this.setResizable(false);
	this.setFocusable(false);
	this.setEnabled(false);
	
	this.setTitle("WoW: TCG preloader");
	
	int r = (int)(Math.random()*10)+1;
	
	imagePanelBean1.setBackgroundImage(ImageLoader.createImageIconAtHomeLocation("wow_bg"+r+".jpg"));
    }
    
    public void setLoading(int percent, String loading){
	this.progressOutlet.setValue(percent);
	this.progressOutlet.setString(percent+" % - "+loading+"...");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagePanelBean1 = new images.ImagePanelBean();
        progressOutlet = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        imagePanelBean1.setBackground(new java.awt.Color(153, 0, 255));
        imagePanelBean1.setEnabled(false);
        imagePanelBean1.setFocusable(false);

        org.jdesktop.layout.GroupLayout imagePanelBean1Layout = new org.jdesktop.layout.GroupLayout(imagePanelBean1);
        imagePanelBean1.setLayout(imagePanelBean1Layout);
        imagePanelBean1Layout.setHorizontalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 721, Short.MAX_VALUE)
        );
        imagePanelBean1Layout.setVerticalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 464, Short.MAX_VALUE)
        );

        jPanel1.add(imagePanelBean1, java.awt.BorderLayout.CENTER);

        progressOutlet.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        progressOutlet.setEnabled(false);
        progressOutlet.setFocusable(false);
        progressOutlet.setPreferredSize(new java.awt.Dimension(146, 50));
        progressOutlet.setString("0% - Loading xxx");
        progressOutlet.setStringPainted(true);
        jPanel1.add(progressOutlet, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private images.ImagePanelBean imagePanelBean1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressOutlet;
    // End of variables declaration//GEN-END:variables
}
