/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadingScreen.java
 *
 * Created on Dec 13, 2011, 9:24:43 PM
 */
package viewControllers;

import images.ImageLoader;
import javax.swing.JFrame;

/**
 *
 * @author Warkst
 */
public class LoadingScreen extends javax.swing.JFrame {

    /** Creates new form LoadingScreen */
    public LoadingScreen() {
	initComponents();
	
	this.setLocationRelativeTo(null);
	
	this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
	this.setResizable(false);
	this.setFocusable(false);
	this.setEnabled(false);
	
	imagePanelBean1.setBackgroundImage(ImageLoader.createImageIconAtHomeLocation("wow_bg2.jpg"));
    }
    
    public void setLoadingLabel(String msg){
	this.loadingLabel.setText(msg);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanelBean1 = new images.ImagePanelBean();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48));
        jLabel1.setText("WoW TCG");

        jLabel2.setText("Developed by Warkst");

        loadingLabel.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        loadingLabel.setText("Loading xxx...");

        org.jdesktop.layout.GroupLayout imagePanelBean1Layout = new org.jdesktop.layout.GroupLayout(imagePanelBean1);
        imagePanelBean1.setLayout(imagePanelBean1Layout);
        imagePanelBean1Layout.setHorizontalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1Layout.createSequentialGroup()
                .add(imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imagePanelBean1Layout.createSequentialGroup()
                        .add(96, 96, 96)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(imagePanelBean1Layout.createSequentialGroup()
                        .add(155, 155, 155)
                        .add(jLabel2))
                    .add(imagePanelBean1Layout.createSequentialGroup()
                        .add(141, 141, 141)
                        .add(loadingLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        imagePanelBean1Layout.setVerticalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1Layout.createSequentialGroup()
                .add(105, 105, 105)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loadingLabel)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private images.ImagePanelBean imagePanelBean1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loadingLabel;
    // End of variables declaration//GEN-END:variables
}
