/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SessionController.java
 *
 * Created on 15-aug-2012, 14:32:23
 */
package viewControllers;

import images.ImageLoader;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import model.CardSnapshot;
import model.Deck;
import network.ConnectionProxy;
import network.MessageHandler;

/**
 *
 * @author Robin jr
 */
public class SessionController extends javax.swing.JPanel implements MouseListener, MouseMotionListener, MessageHandler {  
    private final Deck deck;
    private final HandController handController;
    private final StatusController statusController;
    private final TableController tableController;
    
    private ArrayList<CardController> graveyard;
  
    /** Creates new form SessionController */
    public SessionController(MainFrame callback, Deck playerDeck) {
	this.parent = callback;
	this.deck = playerDeck;
	this.handController = new HandController(this);
	this.graveyard = new ArrayList<CardController>();
	
	// create menu
	this.sessionMenu = new JMenu("Session");
	this.sessionMenu.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
	this.sessionMenu.setBorderPainted(false);
	this.sessionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
	    @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sessionMenuMouseEntered(evt);
            }
	    @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sessionMenuMouseExited(evt);
            }
        });
	
	JMenuItem stop = new JMenuItem("Stop session...");
	stop.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent e) {
		parent.removeMenu(sessionMenu);
		parent.stopSession();
	    }
	});
	this.sessionMenu.add(stop);
	
	parent.addMenu(sessionMenu);
	
	initComponents();
	
	this.statusController = StatusController.createAndStart(statusOutlet);
	
	// add the table controller
	this.tableController = new TableController(this);
	this.tableOutlet.removeAll();
	this.tableOutlet.add(tableController);
	this.tableOutlet.repaint();
	
	this.handOutlet.removeAll();
	this.handOutlet.add(handController);
	this.handOutlet.repaint();
	
	styleComponents();
    }
    
    private void sessionMenuMouseEntered(MouseEvent e){
	this.sessionMenu.setBorderPainted(true);
    }
    
    private void sessionMenuMouseExited(MouseEvent e){
	this.sessionMenu.setBorderPainted(false);
    }
    
    private void styleComponents(){
	this.deckOutlet.setIcon(ImageLoader.scaleImage(ImageLoader.createImageIconAtHomeLocation("template.png"), this.deckOutlet.getPreferredSize()));
	this.resolvedCard.setIcon(ImageLoader.scaleImage(ImageLoader.createImageIconAtHomeLocation("template.png"), this.resolvedCard.getPreferredSize()));
	
	// set the hero
	this.tableController.setMyHero(deck.getHero());
    }
    
    public void updateHand(){
	this.handOutlet.repaint();
	this.handOutlet.validate();
	this.repaint();
	this.validate();
    }
    
    public void setStatusMessage(String message){
	statusController.enqueueMessage(message);
    }
    
    public void addCardToTable(CardController card){
	tableController.addMyCard(card);
    }
    
    public void addCardToResources(CardController card){
	tableController.addMyResource(card);
    }
    
    public void addCardToGraveyard(CardController card){
	graveyard.add(0, card);
    }
    
    public void resolve(CardController card){
	resolvedCardOutlet.removeAll();
	resolvedCardOutlet.add(card.scale(resolvedCard.getPreferredSize()));
	resolvedCardOutlet.repaint();
	resolvedCardOutlet.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideSplit = new javax.swing.JSplitPane();
        masterSplit = new javax.swing.JSplitPane();
        statusPanel = new javax.swing.JPanel();
        statusOutlet = new javax.swing.JLabel();
        mainSplit = new javax.swing.JSplitPane();
        tableOutlet = new javax.swing.JPanel();
        playerOutlet = new javax.swing.JPanel();
        cardsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        graveyardOutlet = new javax.swing.JButton();
        removedFromTheGameOutlet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        deckOutlet = new javax.swing.JButton();
        handOutlet = new javax.swing.JPanel();
        resolvedCardOutlet = new javax.swing.JPanel();
        resolvedCard = new javax.swing.JButton();

        sideSplit.setBorder(null);
        sideSplit.setDividerLocation(500);
        sideSplit.setDividerSize(1);
        sideSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        sideSplit.setResizeWeight(1.0);
        sideSplit.setEnabled(false);
        sideSplit.setFocusable(false);
        sideSplit.setMaximumSize(new java.awt.Dimension(150, 2147483647));
        sideSplit.setMinimumSize(new java.awt.Dimension(150, 0));
        sideSplit.setPreferredSize(new java.awt.Dimension(150, 800));
        sideSplit.setRequestFocusEnabled(false);

        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setPreferredSize(new java.awt.Dimension(1440, 800));
        setLayout(new java.awt.BorderLayout());

        masterSplit.setBorder(null);
        masterSplit.setDividerLocation(30);
        masterSplit.setDividerSize(0);
        masterSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        masterSplit.setEnabled(false);
        masterSplit.setFocusable(false);
        masterSplit.setMinimumSize(new java.awt.Dimension(1440, 800));
        masterSplit.setPreferredSize(new java.awt.Dimension(1440, 800));
        masterSplit.setRequestFocusEnabled(false);

        statusPanel.setMaximumSize(new java.awt.Dimension(1440, 30));
        statusPanel.setMinimumSize(new java.awt.Dimension(1440, 30));
        statusPanel.setPreferredSize(new java.awt.Dimension(1440, 30));
        statusPanel.setLayout(new java.awt.BorderLayout());

        statusOutlet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusOutlet.setText("Status");
        statusOutlet.setFocusable(false);
        statusOutlet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statusOutlet.setRequestFocusEnabled(false);
        statusPanel.add(statusOutlet, java.awt.BorderLayout.CENTER);

        masterSplit.setTopComponent(statusPanel);

        mainSplit.setBorder(null);
        mainSplit.setDividerLocation(570);
        mainSplit.setDividerSize(2);
        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setResizeWeight(1.0);
        mainSplit.setEnabled(false);
        mainSplit.setFocusable(false);
        mainSplit.setPreferredSize(new java.awt.Dimension(2, 770));
        mainSplit.setRequestFocusEnabled(false);

        tableOutlet.setBackground(new java.awt.Color(255, 255, 204));
        tableOutlet.setPreferredSize(new java.awt.Dimension(0, 570));
        tableOutlet.setLayout(new java.awt.BorderLayout());
        mainSplit.setLeftComponent(tableOutlet);

        playerOutlet.setMaximumSize(new java.awt.Dimension(32767, 200));
        playerOutlet.setMinimumSize(new java.awt.Dimension(2, 200));
        playerOutlet.setPreferredSize(new java.awt.Dimension(1000, 200));
        playerOutlet.setLayout(new java.awt.BorderLayout());

        cardsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardsPanel.setEnabled(false);
        cardsPanel.setFocusable(false);
        cardsPanel.setMaximumSize(new java.awt.Dimension(240, 200));
        cardsPanel.setMinimumSize(new java.awt.Dimension(240, 200));
        cardsPanel.setPreferredSize(new java.awt.Dimension(240, 200));
        cardsPanel.setRequestFocusEnabled(false);
        cardsPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 200));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        graveyardOutlet.setText("Gy");
        graveyardOutlet.setMaximumSize(new java.awt.Dimension(50, 50));
        graveyardOutlet.setMinimumSize(new java.awt.Dimension(50, 50));
        graveyardOutlet.setPreferredSize(new java.awt.Dimension(50, 50));
        graveyardOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graveyardOutletActionPerformed(evt);
            }
        });
        jPanel1.add(graveyardOutlet);

        removedFromTheGameOutlet.setText("RftG");
        removedFromTheGameOutlet.setMaximumSize(new java.awt.Dimension(50, 50));
        removedFromTheGameOutlet.setMinimumSize(new java.awt.Dimension(50, 50));
        removedFromTheGameOutlet.setPreferredSize(new java.awt.Dimension(50, 50));
        removedFromTheGameOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removedFromTheGameOutletActionPerformed(evt);
            }
        });
        jPanel1.add(removedFromTheGameOutlet);

        cardsPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deck", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        deckOutlet.setPreferredSize(new java.awt.Dimension(130, 182));
        deckOutlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckOutletActionPerformed(evt);
            }
        });
        jPanel2.add(deckOutlet, java.awt.BorderLayout.CENTER);

        cardsPanel.add(jPanel2, java.awt.BorderLayout.LINE_END);

        playerOutlet.add(cardsPanel, java.awt.BorderLayout.LINE_START);

        handOutlet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        handOutlet.setMinimumSize(new java.awt.Dimension(800, 200));
        handOutlet.setPreferredSize(new java.awt.Dimension(800, 200));
        handOutlet.setLayout(new java.awt.BorderLayout());
        playerOutlet.add(handOutlet, java.awt.BorderLayout.CENTER);

        resolvedCardOutlet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resolved card", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        resolvedCardOutlet.setMaximumSize(new java.awt.Dimension(142, 200));
        resolvedCardOutlet.setMinimumSize(new java.awt.Dimension(142, 200));
        resolvedCardOutlet.setPreferredSize(new java.awt.Dimension(142, 200));
        resolvedCardOutlet.setLayout(new java.awt.BorderLayout());

        resolvedCard.setPreferredSize(new java.awt.Dimension(130, 182));
        resolvedCardOutlet.add(resolvedCard, java.awt.BorderLayout.CENTER);

        playerOutlet.add(resolvedCardOutlet, java.awt.BorderLayout.LINE_END);

        mainSplit.setBottomComponent(playerOutlet);

        masterSplit.setBottomComponent(mainSplit);

        add(masterSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void graveyardOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graveyardOutletActionPerformed
	
    }//GEN-LAST:event_graveyardOutletActionPerformed

    /**
     * Draw a card when left clicking on the deck
     * 
     * @param evt 
     */
    private void deckOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckOutletActionPerformed
	drawCard(1);
    }//GEN-LAST:event_deckOutletActionPerformed

    private void drawCard(int amount) {
	for (int i = 0; i < amount; i++) {
	    CardController drawn = deck.drawCard();
	    if (drawn != null) {
		// add the preview mouse listener to the card upon drawing it and add it to the handcontroller
		handController.addCard(drawn);
	    } else {
		// DECK IS EMPTY
		JOptionPane.showMessageDialog(new JFrame(), "Your deck is empty!", "Can't draw card", JOptionPane.ERROR_MESSAGE);
		break;
	    }
	}
    }
    
    public void prepareAttachingOfCard(CardController toAttach){
	tableController.prepareAttachingOfCard(toAttach);
    }

    private void removedFromTheGameOutletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removedFromTheGameOutletActionPerformed
	setStatusMessage(new Date().toString());
    }//GEN-LAST:event_removedFromTheGameOutletActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JButton deckOutlet;
    private javax.swing.JButton graveyardOutlet;
    private javax.swing.JPanel handOutlet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JSplitPane masterSplit;
    private javax.swing.JPanel playerOutlet;
    private javax.swing.JButton removedFromTheGameOutlet;
    private javax.swing.JButton resolvedCard;
    private javax.swing.JPanel resolvedCardOutlet;
    private javax.swing.JSplitPane sideSplit;
    private javax.swing.JLabel statusOutlet;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel tableOutlet;
    // End of variables declaration//GEN-END:variables
    
    private final JMenu sessionMenu;
    
    private MainFrame parent;
    
    private ArrayList<String> removedftgame;
    // drag from hand:
    private boolean draggingFromHand = false;
    private Point draggingFromHandLastLocation = null;
    private String draggingFromHandCardName = null;
    private CardPanel draggingFromHandCardPanel = null;
    private boolean draggingFromHandCardPanelShown = false;
    private boolean dragging = false;
    private CardPanel draggedCard;
    private static final int GRIDX = 20, GRIDY = 20;
    private List<CardPanel> cards = new ArrayList<CardPanel>();
    /**
     * Registered a mouse click
     * 
     * MAYBE: ADD SELECTED STATE TO PANELS AND ALLOW KEYBOARD INTERACTION?
     * 
     * @param e 
     */
    @Override
    public void mouseClicked(MouseEvent e) {
	// determine the card that was clicked
	Component c = tableOutlet.findComponentAt(e.getX(), e.getY());
	if (!(c.getParent() instanceof CardPanel)) {
	    return;
	}
	c = c.getParent(); // change c to the panel
	final CardPanel clickedCard = (CardPanel) c;
	
//	System.out.println("Clicked on "+c.toString());

	final Point clickedLocation = e.getLocationOnScreen();

	// on right click, make a JPopupDialog
	if (e.getButton() == MouseEvent.BUTTON3) {
	    JPopupMenu popup = new JPopupMenu();

	    JMenuItem readItem = new JMenuItem("Read card...");
	    readItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    //
		    //System.out.println("STUB :: Read card clicked");
		    clickedCard.showCard(clickedLocation);
		}
	    });

	    popup.add(readItem);

	    popup.addSeparator();

	    JMenuItem menuItem = new JMenuItem("Exhaust");
	    if (clickedCard.isExhausted()) {
		menuItem.setText("Ready");
	    }
	    menuItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    //System.out.println("Clicked cardPanel: "+clickedCard.getName());
		    clickedCard.toggleExhaust();
		}
	    });
	    popup.add(menuItem);

	    JMenuItem flipItem = new JMenuItem("Flip");
	    flipItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    clickedCard.toggleFlip();
//		    if (state == ONLINE) {
//			connection.sendSnapshot(clickedCard.getGUID(), clickedCard.getSnapshot());
//		    }
		}
	    });
	    popup.add(flipItem);

	    popup.addSeparator();

	    JMenuItem countersItem = new JMenuItem("Set Counters...");
	    countersItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    boolean validInput = false;
		    int res = 0;
		    do {
			try {
			    String resString = JOptionPane.showInputDialog(new JFrame(), "Counters:", clickedCard.getCounters());

			    // close or cancel
			    if (resString == null) {
				break;
			    }

			    res = Integer.parseInt(resString);

			    //if(resString == JOptionPane.CANCEL_OPTION)

			    validInput = true;
			} catch (Exception ex) {
			    System.err.println("Caught an error: " + ex);
			    // learn to enter numbers faggots
			}

		    } while (!validInput);

		    if (validInput) {
			clickedCard.setCounters(res);
//			if (state == ONLINE) {
//			    connection.sendSnapshot(clickedCard.getGUID(), clickedCard.getSnapshot());
//			}
		    }
		}
	    });

//	    popup.add(countersItem);

	    JMenuItem addCounterItem = new JMenuItem("Add Counter");
	    addCounterItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    clickedCard.setCounters(clickedCard.getCounters() + 1);

//		    if (state == ONLINE) {
//			connection.sendSnapshot(clickedCard.getGUID(), clickedCard.getSnapshot());
//		    }
		}
	    });

	    popup.add(addCounterItem);

	    JMenuItem removeCounterItem = new JMenuItem("Remove Counter");
	    removeCounterItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    clickedCard.setCounters(clickedCard.getCounters() - 1);

//		    if (state == ONLINE) {
//			connection.sendSnapshot(clickedCard.getGUID(), clickedCard.getSnapshot());
//		    }
		}
	    });

	    popup.add(removeCounterItem);

	    popup.add(countersItem);

	    popup.addSeparator();

	    JMenuItem controlItem = new JMenuItem("Take Control!");
	    if (clickedCard.isMyCard()) {
		controlItem.setText("Give Control");
	    }
	    controlItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    System.out.println("STUB :: Switching control of card!");
		}
	    });

	    popup.add(controlItem);

	    popup.addSeparator();

	    JMenuItem toHandItem = new JMenuItem("To Hand");
	    toHandItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    //System.out.println("STUB :: Moving card to hand");
		    moveCardToHandFromPlay(clickedCard);
		}
	    });

	    popup.add(toHandItem);

	    JMenuItem graveyardItem = new JMenuItem("To Graveyard");
	    graveyardItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    //System.out.println("STUB :: Moving card to graveyard");
//		    moveCardToGraveyardFromPlay(clickedCard);
		}
	    });

	    popup.add(graveyardItem);

	    JMenuItem toDeckItem = new JMenuItem("To Top Of Deck");
	    toDeckItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    System.out.println("STUB :: Moving card to top of deck");
		}
	    });

	    popup.add(toDeckItem);

	    JMenuItem removeFromGameItem = new JMenuItem("Remove From Game");
	    removeFromGameItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    System.out.println("STUB :: Removing from the game");
		}
	    });

	    popup.add(removeFromGameItem);

	    popup.addSeparator();

	    // add to top, one to top, one to bot, to bot

	    JMenuItem toTopItem = new JMenuItem("Bring To Top");
	    toTopItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
//		    clickedCard.toFront(getTopLayer()+1);

		    // remove it and add it to the back = put on top
		    cards.remove(clickedCard);
		    cards.add(clickedCard);

//		    redrawCard(clickedCard);

		    redrawAllCards();
		}
	    });
	    popup.add(toTopItem);

	    JMenuItem oneUpItem = new JMenuItem("Move One Up");
	    oneUpItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    // remove it and add it to its previous place + 1
		    int index = cards.indexOf(clickedCard);
		    if (index < cards.size() - 1) {
			cards.remove(clickedCard);
			cards.add(index + 1, clickedCard);
		    }

		    redrawAllCards();
		}
	    });
	    popup.add(oneUpItem);

	    JMenuItem oneDownItem = new JMenuItem("Move One Down");
	    oneDownItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
		    // remove it and add it to its previous place - 1
		    int index = cards.indexOf(clickedCard);
		    if (index > 0) {
			cards.remove(clickedCard);
			cards.add(index - 1, clickedCard);
		    }

		    redrawAllCards();
		}
	    });
	    popup.add(oneDownItem);

	    JMenuItem toBackItem = new JMenuItem("Bring To Back");
	    toBackItem.addActionListener(new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
//		    clickedCard.toFront(getTopLayer()+1);

		    // remove it and add it to the front = put in top
		    cards.remove(clickedCard);
		    cards.add(0, clickedCard);

//		    redrawCard(clickedCard);

		    redrawAllCards();
		}
	    });
	    popup.add(toBackItem);

	    popup.show(c, e.getX() - c.getX(), e.getY() - c.getY());
	} else if (e.getButton() == MouseEvent.BUTTON1 && e.isShiftDown()) {
	    clickedCard.toggleExhaust();
//	    this.repaint();
	    System.out.println(" should exhaust ");
	    
	} else if (e.getButton() == MouseEvent.BUTTON1 && e.isControlDown()) {
	    
	    System.out.println("should delete");
	    
	    // ctrl+click -> card to graveyard
//	    moveCardToGraveyardFromPlay(clickedCard);
	} 
    }

    /**
     * MAKE SURE THIS ONLY WORKS FOR CARDS THAT I OWN
     * 
     * Maybe: dress up the dragged card (add border or just semi transparent color layer)
     * DOESNT WORK, AT LEAST NOT WITH BORDERS FOR SOME ODD REASON
     * 
     * @param e 
     */
    @Override
    public void mousePressed(MouseEvent e) {
	// only drag with left mouse button
//	if (e.getButton() == MouseEvent.BUTTON1 && !dragging && !e.isControlDown()) {
	if (e.getButton() == MouseEvent.BUTTON1 && !dragging && !e.isControlDown() && !e.isShiftDown()) {
	    
	    System.out.println("should start drag");
	    
	    if(e.isControlDown()) return;
	    
	    // reset drag and start
	    draggedCard = null;
	    dragging = true;

	    // find component that was clicked
	    Component c = tableOutlet.findComponentAt(e.getX(), e.getY());
	    if (!(c.getParent() instanceof CardPanel)) {
		return;
	    }
	    c = c.getParent(); // change c to the panel

	    // find location of click
	    Point compLoc = c.getLocation();

	    // find card and register it as drag card
	    draggedCard = (CardPanel) c;

//	    System.out.println("Clicked on card " + draggedCard.getCardName() + " on layer " + tableOutlet.getLayer(c));

	    // pick up card
	    draggedCard.setLocation(compLoc);
	    draggedCard.setBounds((int) compLoc.getX(), (int) compLoc.getY(), (int) c.getWidth(), (int) c.getHeight());

	    // remove card from its layer and add to drag layer
	    tableOutlet.remove(draggedCard);
	    tableOutlet.add(draggedCard, JLayeredPane.DRAG_LAYER);

	    // trigger redraw
	    tableOutlet.validate();

	    // set cursor to drag
	    tableOutlet.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
	}
    }

    /**
     * gets triggered after ctrl-c + alt-c
     * 
     * @param e 
     */
    @Override
    public void mouseReleased(MouseEvent e) {
	dragging = false;
	if (e.getButton() == MouseEvent.BUTTON1) {
//	    if (!dragging || draggedCard == null) {
//		return;
//	    } else {
//		dragging = false;
//	    }
	    if(draggedCard == null){
		return;
	    }

	    // reset cursor
	    tableOutlet.setCursor(null);

	    // remove card from drag layer
	    tableOutlet.remove(draggedCard);

	    // add card to its previous layer
	    tableOutlet.add(draggedCard, new Integer(JLayeredPane.PALETTE_LAYER + cards.indexOf(draggedCard)));

//	    System.out.println("Released card " + draggedCard.getCardName() + " on layer " + tableOutlet.getLayer(draggedCard));

	    // broadcast this!!
	   
	}
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void mouseDragged(MouseEvent e) {
	
	// is called fast
	
	if (e.getButton() == MouseEvent.BUTTON1) {
	    if (draggedCard == null) {
		return;
	    }
	    if (!dragging) {
		dragging = true;
	    }

	    //	int x = e.getX()+dx;
	    int x = e.getX() - 10;
	    //	int y = e.getY()+dy;
	    int y = e.getY() - 10;

	    // snap to grid
	    x /= GRIDX;
	    x *= GRIDX;

	    y /= GRIDY;
	    y *= GRIDY;
	    
//	    if(x<0)x=0;
//	    if(x+draggedCard.getWidth()>mainPanel.getWidth())
//	    if(y<mainPanel.getLocationOnScreen().getY()) y = mainPanel.getY();
//	    if(y+draggedCard.getHeight()>=mainPanel.getHeight()+mainPanel.getY()) y = mainPanel.getHeight()+mainPanel.getY();

	    // redraw the card at its new location
	    draggedCard.setLocation(x, y);
	}
    }

    @Override
    public void mouseMoved(MouseEvent e) {
    }

    public void startSession(ConnectionProxy conn) {
	// have connection
//	this.connection = conn;

	// put hero card into play
//	spawnCard(deck.getHero());
	
//	startGame(ONLINE);
    }


    private void resetLayout() {
	// empty hand

	// clear everything on the table
	tableOutlet.removeAll();

	// add background again
    }

    private void redrawAllCards() {
	tableOutlet.removeAll();

//	for (CardPanel cardPanel : myCards) {
//	    mainPanel.add(cardPanel, new Integer(JLayeredPane.PALETTE_LAYER+myCards.indexOf(cardPanel)));
//	}
	for (int i = 0; i < cards.size(); i++) {
	    tableOutlet.add(cards.get(i), new Integer(JLayeredPane.PALETTE_LAYER + i));
	}

	tableOutlet.validate();
    }

    private void spawnCard(String cardName) {
//	Card card = model.generateCardByName(model.getCardByName(cardName).getType(), cardName);
//
//	if (card != null) {
//	    CardPanel cardPanel = new CardPanel(card, cards.size());
//	    cardPanel.setBounds(40, 40, 60, 60);
//
//	    addToPlay(cardPanel);
//
////	    if (state == ONLINE) {
////		//send gui update
////		connection.sendGUIMessage(cardPanel);
////	    }
//	}
    }

    /**
     * Supposed to be called by receiveForeignCard
     * 
     * @param cardName
     * @param GUID 
     */
    private void spawnCardWithGUID(String cardName, String GUID) {
//	Card card = model.generateCardByName(model.getCardByName(cardName).getType(), cardName);
//
//	if (card != null) {
//	    CardPanel cardPanel = new CardPanel(card, cards.size(), GUID);
//	    cardPanel.setBounds(40, 40, 60, 60);
//
//	    addToPlay(cardPanel);
//
////	    if (state == ONLINE) {
////		connection.sendGUIMessage(cardPanel);
////	    }
//	}
    }

    private void addToPlay(CardPanel cardPanel) {
	System.out.println("Adding a card to play (" + cardPanel.getCardName() + ")!");

	cards.add(cardPanel);

//	int layer = new Integer(JLayeredPane.PALETTE_LAYER + cards.indexOf(cardPanel));

	tableOutlet.add(cardPanel, new Integer(JLayeredPane.PALETTE_LAYER + cards.indexOf(cardPanel)));
	tableOutlet.validate();
	tableOutlet.repaint();
    }

    private void addToPlay(CardPanel cardPanel, Point loc) {
	cardPanel.setLocation(loc);
	addToPlay(cardPanel);
    }

    private void moveCardToHandFromPlay(CardPanel cardPanel) {
	tableOutlet.remove(cardPanel);

	cardPanel.setVisible(false);
//	hand.add(cardPanel.getCard().getName());
//	leftList.setListData(hand.toArray(new String[0]));

	tableOutlet.validate();
	tableOutlet.repaint();
    }

    // Message Handler protocol
    @Override
    public void receiveTextMessage(String msg) {
//	addToChat("Stranger: " + msg);
    }

    @Override
    public void receiveForeignCard(CardPanel cardPanel) {
	addToPlay(cardPanel);
    }

    @Override
    public void moveCardWithGUIDToLocation(String GUID, Point location) {
	CardPanel moveMe = findCardPanelForGUID(GUID);
	if (moveMe != null) {
	    moveMe.setLocation(location);
	}
	tableOutlet.validate();
    }

    @Override
    public void applySnapshotToCardWithGUID(String GUID, CardSnapshot snapshot) {
	CardPanel changeMe = findCardPanelForGUID(GUID);
	if (changeMe != null) {
	    changeMe.applySnapshot(snapshot);
	}
	tableOutlet.validate();
    }
    
    
    private void rollDie(int sides) {
	int outcome = 1 + (int) (Math.random() * sides);
//	sendMessage("rolled a " + outcome + " with a " + sides + " sided die!");
    }

    private CardPanel findCardPanelForGUID(String GUID) {
	CardPanel ret = null;
	for (CardPanel cardPanel : cards) {
	    if (cardPanel.getGUID().compareTo(GUID) == 0) {
		ret = cardPanel;
		break;
	    }
	}
	return ret;
    }

    private boolean isMyCardPanel(String GUID) {
	boolean ret = false;
	for (CardPanel cardPanel : cards) {
	    if (cardPanel.getGUID().compareTo(GUID) == 0) {
		ret = true;
		break;
	    }
	}
	return ret;
    }
}
