/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameFrameController.java
 *
 * Created on Oct 25, 2011, 1:25:29 PM
 */
package gui;

import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import network.MessageHandler;
import network.MessageHandlerProvider;

/**
 *
 * @author Warkst
 */
public class GameFrameController extends javax.swing.JFrame implements MessageHandlerProvider {

    private final GUIMaster master;
    private ViewController activeViewController;

    /** Creates new form GameFrameController */
    public GameFrameController(final GUIMaster master, ViewController initialViewController) {
	this.master = master;
	initComponents();

	this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

	// set closeListener to safely close the connections
	addWindowListener(new WindowAdapter() {

	    @Override
	    public void windowClosing(WindowEvent e) {
		master.shutdown();
	    }
	});

	this.getContentPane().removeAll();
	this.getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER));
	this.activeViewController = initialViewController;
	this.getContentPane().add(initialViewController.getView());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Game Client");
        setBounds(0,0,(int)Toolkit.getDefaultToolkit().getScreenSize().width, (int)Toolkit.getDefaultToolkit().getScreenSize().height-30);
        setFocusable(false);
        setResizable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 554, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void setViewController(final ViewController viewController) {
	activeViewController = viewController;
	// set new view controller in the EDT
	SwingUtilities.invokeLater(new Runnable() {
	    public void run() {
		Container content = getContentPane();
		content.removeAll();
		content.add(viewController.getView());
		setContentPane(content);
		repaint();
		viewController.electFirstResponder();
		setVisible(true);
	    }
	});
    }

    public void shutdown() {
	this.dispose();
    }

    public MessageHandler getMessageHandler(String handlerTag) {
	// there is only one message handler, the tag isn't needed
	return activeViewController;
    }
}
