/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadingViewController.java
 *
 * Created on Nov 1, 2011, 5:19:31 PM
 */
package gui;

import images.ImageLoader;
import java.awt.Dimension;
import javax.swing.JPanel;
import network.Message;

/**
 *
 * @author Warkst
 */
public class LoadingViewController extends javax.swing.JPanel implements ViewController {

    /** Creates new form LoadingViewController */
    public LoadingViewController() {
	initComponents();
	
	progressbarLoading.setStringPainted(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanelBean1 = new images.ImagePanelBean();
        labelLoading = new javax.swing.JLabel();
        progressbarLoading = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(1440, 880));
        setMinimumSize(new java.awt.Dimension(1440, 880));
        setPreferredSize(new java.awt.Dimension(1440, 880));
        setSize(new java.awt.Dimension(1440, 880));

        imagePanelBean1.setBackgroundImage(ImageLoader.scaleImage(ImageLoader.createImageIconAtHomeLocation("parchment.jpg"), new Dimension(1440,880)));

        labelLoading.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        labelLoading.setText("Loading...");

        progressbarLoading.setMaximumSize(new java.awt.Dimension(32767, 80));
        progressbarLoading.setPreferredSize(new java.awt.Dimension(146, 40));
        progressbarLoading.setSize(new java.awt.Dimension(146, 40));
        progressbarLoading.setStringPainted(true);

        org.jdesktop.layout.GroupLayout imagePanelBean1Layout = new org.jdesktop.layout.GroupLayout(imagePanelBean1);
        imagePanelBean1.setLayout(imagePanelBean1Layout);
        imagePanelBean1Layout.setHorizontalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .add(imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, imagePanelBean1Layout.createSequentialGroup()
                        .add(progressbarLoading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(78, 78, 78))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, imagePanelBean1Layout.createSequentialGroup()
                        .add(labelLoading)
                        .add(561, 561, 561))))
        );
        imagePanelBean1Layout.setVerticalGroup(
            imagePanelBean1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelBean1Layout.createSequentialGroup()
                .add(288, 288, 288)
                .add(labelLoading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(311, 311, 311)
                .add(progressbarLoading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(imagePanelBean1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(imagePanelBean1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private images.ImagePanelBean imagePanelBean1;
    private javax.swing.JLabel labelLoading;
    private javax.swing.JProgressBar progressbarLoading;
    // End of variables declaration//GEN-END:variables

    public JPanel getView() {
	return this;
    }

    public void electFirstResponder() {
	// do nothing
    }

    public void handleMessage(Message message) {
	// do nothing
    }
    
    public void setLabel(String s){
	labelLoading.setText(s);
    }
    
    public void setProgress(int n){
	progressbarLoading.setValue(n);
    }
}
